### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by M0dEx** [simiooo/quincy_sui#1]
Could the UI be made localizable - have a switch to change the language to English or other languages?

P. S.: I really love the project, and it could bring a much-needed easier way to use Quincy.

**Comment by simiooo** [comment]
> Could the UI be made localizable - have a switch to change the language to English or other languages?
> 
> P. S.: I really love the project, and it could bring a much-needed easier way to use Quincy.

This feature will be added in next release ( After several days maybe ) . This is a nice suggestion , thanks .

**Comment by simiooo** [comment]
> Could the UI be made localizable - have a switch to change the language to English or other languages?
> 
> P. S.: I really love the project, and it could bring a much-needed easier way to use Quincy.

The Localization feature is added in new release (v1.0.1-beta.1) .
